# Topic

Personally I am a huge fan of chess and also video games and one of the main ways that they rank competitors in those two is through Elo ratings. This user guide will mainly focus on explaining how to build and also apply an Elo rating system for head-to-head competitions. This will explore how Elo rating measure different things like, competitor skill levels, how ratings change after match outcomes, and how rating difference can be used to predict future performance.

This guide will also include basic step-by-step instructions for implementing an Elo rating system in R using match outcome data and will also introduce a few helpful R packages. This guide will also explain when Elo rankings work well and also may not work as well compared to other ranking systems, like Glicko.


::: callout-note
# Comments/suggestions

Please help me out and define your terms (I appreciate chess and video games, but I know very little about either one) well (you can footnote them, since your user guide will probably assume that the reader knows more than I do). 

I wonder if you could find ratings datasets for e.g. Starcraft, Pokemon TCG, etc. as well as chess -- Starcraft is a bit more interesting, I think, because iirc it has more than 2 players in a game? At any rate, I think it might be interesting to see how these models play out with slightly different game structures. 

:::